# User Settings | Edit there as per required

title: Etherboost
url: "http://etherboost.github.io"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    Etherboost blog

author: Etherboost
# This description will show up in google search results
# (for index page) etc.
description: >
    Etherboost is a producer of decentralized autonomous organizations governed by smart contracts on the Ethereum blockchain.

# This will what will show against &copy; in the footer
copyright: Etherboost

permalink: /blog/:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Etherboost is a producer of decentralized autonomous organizations governed by smart contracts on the Ethereum blockchain.

about_footer: true

twitter_username: Etherboost
github_username: Etherboost

favicon: true
favicon_location: "/images/favicon.ico"

profile_picture: "/images/logo.svg"
logo: "/images/logo.svg"
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-75000235-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "/images/logo.svg" # This will show in facebook thumbnails
twitter_image: "https://pbs.twimg.com/profile_images/708316986263080961/q-AwaslD_400x400.jpg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
